#version: "3.0"
#services:
#  elm-mysql:
#    image: mysql
#    container_name: elm-mysql
#    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: elm123
#      MYSQL_DATABASE: customer_service
#  elm-test:
#    container_name: elm-test
#    image: elm-spring
#    restart: always
#    environment:
#      - SPRING_PROFILES_ACTIVE=mysql
#    ports:
#      - 8080:8080
version: "3.0"
services:
  elm-mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: elm-mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123QWEqwe
  elm-test:
    container_name: elm-test
    image: elm-spring-ms
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=ms
    ports:
    - 8080:8080