version: "3.0"
services:
  database-mysql:
    image: mysql
    container_name: database-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: database123
      MYSQL_DATABASE: customer_service
  spring-app:
    container_name: spring-app
    image: spring-app
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - 8080:8080