version: "3.0"
services:
  elm-mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: elm-mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123QWEqwe
  elm-test:
    container_name: elm-test
    image: elm-spring-ms
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=ms
    ports:
    - 8080:8080