version: "3.0"
services:
  elm-mysql:
    image: mysql
    container_name: elm-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: elm123
      MYSQL_DATABASE: customer_service
  elm-test:
    container_name: elm-test
    image: elm-test-3
    restart: always
    ports:
    - 8080:8080