version: "3.0"
services:
  database-mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: database-mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123QWEqwe
  spring-app:
    container_name: spring-app
    image: spring-app
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=ms
    ports:
    - 8080:8080