spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_service?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: elm123
    driver-class-name: com.mysql.jdbc.Driver

  security:
    user:
      name: elm
      password: SAeictcyguhpIDE9KayBGTGDkywaNR0Soph
  jpa:
    hibernate:
      ddl-auto: update
