spring:
  datasource:
    url: jdbc:sqlserver://database-mssql;databaseName=customer_service
    username: sa
    password: 123QWEqwe
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  security:
    user:
      name: user
      password: SAeictcyguhpIDE9KayBGTGDkywaNR0Soph
  jpa:
    hibernate:
      ddl-auto: update