spring:
  datasource:
    url: jdbc:mysql://database-mysql/customer_service?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: database123
    driver-class-name: com.mysql.jdbc.Driver

  security:
    user:
      name: user
      password: SAeictcyguhpIDE9KayBGTGDkywaNR0Soph
  jpa:
    hibernate:
      ddl-auto: update